name: benchmark
version: 5.0.0
description: >
  Benchmark, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  browser: any
  built_collection: '>=2.0.0 <4.0.0'
  built_value: ^5.0.0

dev_dependencies:
  build: ^0.11.1
  build_runner: ^0.6.0
  built_value_generator: ^5.0.0
  source_gen: ^0.7.0
  quiver: '>=0.21.0 <0.28.0'
  test: any
