name: benchmark
version: 4.3.4
description: >
  Benchmark, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  browser: any
  built_collection: ^2.0.0
# built_value: ^4.3.4
  built_value:
    path: ../built_value

dev_dependencies:
  build: ^0.10.0
  build_runner: ^0.4.0
# built_value_generator: ^4.3.4
  built_value_generator:
    path: ../built_value_generator
  source_gen: ^0.7.0
  quiver: '>=0.21.0 <0.26.0'
  test: any
