name: benchmark
version: 0.4.0
description: >
  Benchmark, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  browser: any
  built_collection: '^1.0.0'
  built_value: '^0.4.0'

dev_dependencies:
  build: '^0.4.0'
  built_value_generator: '^0.4.0'
  source_gen: '>=0.5.0+03 <0.6.0'
  quiver: '>=0.21.0 <0.24.0'
  test: any
