name: benchmark
version: 1.2.1
description: >
  Benchmark, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  browser: any
  built_collection: ^1.0.0
  built_value: ^1.2.1

dev_dependencies:
  build: ^0.9.0
  build_runner: ^0.3.2
  built_value_generator: ^1.2.1
  source_gen: ^0.7.0
  quiver: '>=0.21.0 <0.26.0'
  test: any
