name: benchmark
version: 5.5.4
description: >
  Benchmark, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  browser: any
  built_collection: '>=2.0.0 <4.0.0'
  built_value: ^5.5.4

dev_dependencies:
  build_runner: ^0.9.0
  built_value_generator: ^5.5.4
  quiver: '>=0.21.0 <3.0.0'
  test: ^1.0.0
