name: benchmark
version: 5.1.2
description: >
  Benchmark, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  browser: any
  built_collection: '>=2.0.0 <4.0.0'
# built_value: ^5.1.2
  built_value:
    path: ../built_value

dev_dependencies:
  build: ^0.11.1
  build_runner: ^0.6.0
# built_value_generator: ^5.1.2
  built_value_generator:
    path: ../built_value_generator
  source_gen: ^0.7.0
  quiver: '>=0.21.0 <0.29.0'
  test: any
