name: benchmark
version: 5.5.1
description: >
  Benchmark, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  browser: any
  built_collection: '>=2.0.0 <4.0.0'
  built_value: ^5.5.1

dev_dependencies:
  build_runner: ^0.8.0
  built_value_generator: ^5.5.1
  quiver: '>=0.21.0 <0.30.0'
  test: any

dependency_overrides:
  built_value:
    path: ../built_value
  built_value_generator:
    path: ../built_value_generator
