name: example
version: 2.0.0
description: >
  Just an example, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  meta: ^1.0.4
  built_collection: ^1.0.0
  built_value: ^2.0.0

dev_dependencies:
  build: ^0.9.0
  build_runner: ^0.3.2
  built_value_generator: ^2.0.0
  source_gen: ^0.7.0
  quiver: '>=0.21.0 <0.26.0'
  test: any
