name: example
version: 5.1.1
description: >
  Just an example, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  meta: ^1.0.4
  built_collection: '>=2.0.0 <4.0.0'
  built_value: ^5.1.1

dev_dependencies:
  build: ^0.11.1
  build_runner: ^0.6.0
  built_value_generator: ^5.1.1
  source_gen: ^0.7.0
  quiver: '>=0.21.0 <0.29.0'
  test: any
