name: built_value
version: 0.0.1
description: >
  Code generation supporting value types with builders.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built-value-dart
dependencies:
  source_gen: '>=0.3.0'
dev_dependencies:
  unittest: '>=0.10.0'
