name: built_value_generator
version: 4.1.0
description: >
  Value types with builders, Dart classes as enums, and serialization.
  This library is the dev dependency.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=1.12.0-dev.5.10 <2.0.0'

dependencies:
  analyzer: '>=0.29.0 <0.31.0'
  build: ^0.10.0
  built_collection: ^1.0.0
  built_value: ^4.1.0
  source_gen: ^0.7.0
  quiver: '>=0.21.0 <0.26.0'

dev_dependencies:
  build_test: ^0.6.0
  build_runner: ^0.4.0
  test: any
