name: chat_example
version: 2.1.0
description: >
  Just an example, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  built_collection: ^1.0.0
  built_value: ^2.1.0
  shelf: ^0.6.0
  shelf_proxy: ^0.1.0
  shelf_web_socket: ^0.2.1
  web_socket_channel: ^1.0.0

dev_dependencies:
  build: ^0.9.0
  build_runner: ^0.3.2
  built_value_generator: ^2.1.0
  source_gen: ^0.7.0
  test: any
