name: chat_example
version: 0.4.3
description: >
  Just an example, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  built_collection: '^1.0.0'
  built_value: ^0.4.3
  package_resolver: ^1.0.0
  route: '>=0.4.6'

dev_dependencies:
  build: '^0.4.0'
  built_value_generator: ^0.4.3
  source_gen: '>=0.5.0+03 <0.6.0'
  test: any
