name: end_to_end_test
version: 0.5.2
description: >
  Tests, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  meta: ^1.0.4
  built_collection: ^1.0.0
# built_value: ^0.5.2
  built_value:
    path: ../built_value

dev_dependencies:
  build: ^0.7.0
  build_runner: ^0.3.0
# built_value_generator: ^0.5.2
  built_value_generator:
    path: ../built_value_generator
  source_gen: '>=0.5.0+03 <0.6.0'
  quiver: '>=0.21.0 <0.24.0'
  test: any
